# frozen_string_literal: true

require "rails/generators"
require "rails/generators/base"
require "rails/generators/migration"

module SwalRails
  module Generators
    # Installs the "don't show this again" preferences feature on top of an
    # existing `rails g swal_rails:install`: a migration for
    # `swal_rails_dismissed_alerts`, the engine mount (suppressions API),
    # and `config.preferences_enabled = true` in the initializer.
    #
    # Safe to re-run — each step is guarded and skipped if already present.
    class PreferencesGenerator < Rails::Generators::Base
      include Rails::Generators::Migration

      source_root File.expand_path("templates", __dir__)

      class_option :uuid, type: :boolean, default: false,
                          desc: "Use uuid (instead of bigint) for owner_id, for apps with UUID primary keys"
      class_option :skip_route, type: :boolean, default: false,
                                desc: "Don't mount SwalRails::Engine in config/routes.rb"

      def self.next_migration_number(dirname)
        next_number = current_migration_number(dirname) + 1
        ActiveRecord::Migration.next_migration_number(next_number)
      end

      def copy_migration
        migration_template "create_swal_rails_dismissed_alerts.rb.tt",
                           "db/migrate/create_swal_rails_dismissed_alerts.rb"
      end

      def mount_engine
        return if options[:skip_route]

        routes_file = "config/routes.rb"
        unless file_exists?(routes_file)
          say_status(:warn, "#{routes_file} not found, skipping route mount", :yellow)
          return
        end

        if File.read(File.join(destination_root, routes_file)).include?("SwalRails::Engine")
          say_status(:skip, "SwalRails::Engine already mounted in #{routes_file}", :yellow)
          return
        end

        route 'mount SwalRails::Engine => "/swal_rails"'
      end

      def enable_preferences
        initializer_file = "config/initializers/swal_rails.rb"
        unless file_exists?(initializer_file)
          say_status(:warn,
                     "#{initializer_file} not found — run `rails g swal_rails:install` first, " \
                     "then set config.preferences_enabled = true manually", :yellow)
          return
        end

        content = File.read(File.join(destination_root, initializer_file))

        if content.match?(/^\s*config\.preferences_enabled\s*=\s*true/)
          say_status(:skip, "config.preferences_enabled already enabled in #{initializer_file}", :yellow)
          return
        end

        # Initializers generated by `swal_rails:install` (>= 0.6.0) ship a
        # commented placeholder for these settings — uncomment it in place.
        if content.include?("# config.preferences_enabled = false")
          gsub_file initializer_file, /^  # (config\.preferences_enabled = )false$/, '  \1true'
          gsub_file initializer_file, /^  # (config\.current_user_method = .+)$/, '  \1'
          gsub_file initializer_file, /^  # (config\.preferences_parent_controller = .+)$/, '  \1'
          return
        end

        # Older initializer without the placeholder — append the full block.
        inject_into_file initializer_file, "#{preferences_snippet}\n", before: /\nend\s*\z/
      end

      def show_readme
        readme_text = <<~TXT

          swal_rails preferences installed.

          Next steps:
            1. bin/rails db:migrate
            2. Mark a confirm/flash/turbo_stream as muteable with a unique key:
                 <%= button_to "Delete", post_path(@post), method: :delete,
                       data: { turbo_confirm: "Sure?", swal_mute_key: "posts.destroy" } %>
                 swal_flash :notice, "Saved", mute_key: "posts.saved"
            3. Reset suppressions from the console:
                 SwalRails::Preferences.reset_all
                 SwalRails::Preferences.reset(key: "posts.saved")
                 SwalRails::Preferences.reset(owner: current_user)
                 SwalRails::Preferences.reset(owner: current_user, key: "posts.saved")
        TXT
        say readme_text, :green
      end

      private

      def migration_version
        "[#{ActiveRecord::Migration.current_version}]"
      end

      def preferences_snippet
        [
          "",
          "  # \"Don't show this again\" preferences (rails g swal_rails:preferences).",
          "  # Suppressions are stored in swal_rails_dismissed_alerts for known",
          "  # owners, localStorage for guests.",
          "  config.preferences_enabled = true",
          "",
          "  # Resolves the current owner; nil/missing means \"guest\" (localStorage fallback).",
          "  # Devise: :current_user  ·  Rodauth: :rodauth_account  ·  custom: your own method.",
          "  config.current_user_method = :current_user",
          "",
          "  # Parent class for SwalRails::SuppressionsController, e.g. \"ApplicationController\"",
          "  # if it needs to share before_actions (auth, CSRF) with the rest of your app.",
          "  config.preferences_parent_controller = \"ActionController::Base\""
        ].join("\n")
      end

      def file_exists?(path)
        File.exist?(File.join(destination_root, path))
      end
    end
  end
end
